loopback_interfaces:
  - { id: 1, ip: 1.1.1.1 }
  - { id: 2, ip: 2.2.2.2 } 
  - { id: 3, ip: 3.3.3.3 }
  - { id: 4, ip: 4.4.4.4 }
  - { id: 5, ip: 5.5.5.5 }
  - { id: 6, ip: 6.6.6.6 } # Add more as needed; loop over this list